language: cpp
compiler: gcc
install:
        - sudo apt-get update -qq
        - sudo apt-get install -qq libopenmpi-dev
script:
        - mkdir build
        - cd build
        - cmake ../src/ && make -j4 && make test

# Ubuntu 14.04 Trusty support
sudo: required
dist: trusty

addons:
  apt:
    sources:
    # add PPAs with more up-to-date toolchains
    - ubuntu-toolchain-r-test
    packages:
    # install toolchains
    - gcc-5
    - g++-5
