language: cpp
compiler: gcc
before_install:
        - pip install --user cpp-coveralls
before_script:
        - mkdir -p build
        - cd build
script:
        - cmake -DhdfsEnabled=OFF ../src/ && make &&  make test
after_success:
        - coveralls --exclude lib --exclude tests --gcov-options '\-lp'



# Ubuntu 14.04 Trusty support
sudo: required
dist: trusty

addons:
  apt:
    sources:
    # add PPAs with more up-to-date toolchains
    - ubuntu-toolchain-r-test
    packages:
    # install toolchains
    - gcc-5
    - g++-5
    - libopenmpi-dev
    - valgrind
