language: cpp
compiler: gcc
script:
        - mkdir -p build
        - cd build
        - cmake -DhdfsEnabled=OFF ../src/ && make

# Ubuntu 14.04 Trusty support
sudo: required
dist: trusty

addons:
  apt:
    sources:
    # add PPAs with more up-to-date toolchains
    - ubuntu-toolchain-r-test
    packages:
    # install toolchains
    - gcc-5
    - g++-5
    - libopenmpi-dev
