language: cpp
compiler: gcc
before_install:
        - pip install --user cpp-coveralls
        - mkdir -p ~/build/mtcs/faster/build
          #- mkdir -p ~/gtest-build && cd ~/gtest-build && cmake /usr/src/gtest/ && make && cp *.a ~/build/mtcs/faster/build
        - mkdir -p ~/gtest-build && cd ~/gtest-build && cmake /usr/src/gtest/ && make && cp *.a /usr/lib
        - cd ~/build/mtcs/faster/build
before_script:
script:
        #- cmake -DGTEST_MAIN_LIBRARY:FILEPATH=libgtest_main.a -DGTEST_LIBRARY:FILEPATH=libgtest.a -DhdfsEnabled=OFF -DCMAKE_BUILD_TYPE=DEBUG -DCOVERALLS=ON  ~/build/mtcs/faster/src/ && make -j 3 &&  make -j 3 test
        - cmake -DhdfsEnabled=OFF -DCMAKE_BUILD_TYPE=DEBUG -DCOVERALLS=ON  ~/build/mtcs/faster/src/ && make -j 3 &&  make -j 3 test
after_success:
        - coveralls --exclude tests --explude test --exclude examples --gcov-options '\-lp'



# Ubuntu 14.04 Trusty support
sudo: required
dist: trusty

addons:
  apt:
    sources:
    # add PPAs with more up-to-date toolchains
    - ubuntu-toolchain-r-test
    packages:
    - gcc-5
    - g++-5
    - libopenmpi-dev
    - valgrind
    - libgtest-dev
